name: 'Verify chart'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-chart-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: Setup Kind tool
        run: go install sigs.k8s.io/kind@v0.20.0

      - name: Create cluster with Ingress
        run: kind create cluster --config .github/cluster/kind-cluster.yaml

      - uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Install Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl rollout status deployment ingress-nginx-controller -n ingress-nginx
          # sleep 10s
          # kubectl wait --namespace ingress-nginx \
          #   --for=condition=ready pod \
          #   --selector=app.kubernetes.io/component=controller \
          #   --timeout=90s

      - name: Install chart
        run: |
          helm upgrade --install sample-chart ./sample-chart
          sleep 10s
          kubectl wait --for=condition=ready pod \
            --selector=app.kubernetes.io/name=sample-chart \
            --timeout=90s

      - name: Verify chart
        run: |
          curl http://sample-chart.127.0.0.1.nip.io
