name: 'Verify chart'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-chart-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Install chart
        run: |
          helm upgrade --install sample-chart ./sample-chart